### PR TITLE
Loosen name and path validation to accomodate IDs in REST urls

### PR DESCRIPTION
**Pull request by baer**
PR to correct https://github.com/TestArmada/drydock/issues/1 and https://github.com/TestArmada/drydock/issues/2

### CODE REVIEW

**Comment by divmain** [comment]
Thanks for this!  It makes me think, though, that there will be certain code points that should not be allowed - which is probably why I limited the set of code points originally.  For example, `?` should definitely not be part of a URL's path.  Also spaces and possibly unescaped-`%`.  Thoughts?

**Edit:** From the [RFC](http://tools.ietf.org/html/rfc3986#section-3.3), looks like the following are valid characters in URI path segment: `unreserved`, `pct-encoded`, `sub-delims`, `":"`, `"@"`.  These character sets are defined in the [appendix](http://tools.ietf.org/html/rfc3986#appendix-A).

**Comment by baer** [comment]
I think you're right and really it should be using [String.url](https://github.com/hapijs/joi/blob/master/API.md#stringurioptions) but since it's only a URI fragment that was impractical. I suppose I could prepend `http://localhost` before validation. That would involve a clone for each validation step but since it's a 1 time startup cost that should be okay. Happy to do that if you'd prefer it. 

As for things like unescaped `%` and query params - I agree but that seems like polish whereas the ability to use this with a REST api seems like a core feature.

**Comment by divmain** [comment]
It's possible that Hapi will error out if you try to define a path with an invalid character.  Would you mind trying that?  If it does, I think I'll merge this PR as-is.  If not, it'll be worth exploring the `http://localhost` idea, or a regex based on RFC 3986 (`/([A-Za-z0-9\-\._~]|[\!$&'\(\)\*\+,;=']|(%[A-Za-z0-9])|\/)+/` may work).

**Comment by baer** [comment]
Sure thing. While I'm in there do you have any changes you want me to make with the validation of `name`. I also made that one generic.

**Comment by divmain** [comment]
I think the permissive name validation should be fine.

**Comment by divmain** [comment]
#1 and #2 have been resolved.

**Pull request closed without merging**
