### PR TITLE
Add support for specifying status codes

### PR DESCRIPTION
**Pull request by biglovisa**
This PR adds support for specifying which status code a registered route should respond with.

### CODE REVIEW

**Comment by biglovisa** [comment]
ping @divmain 
This is the last change needed for us to remove the dependency on our fork and use this project instead. This change also opens up the possibility to specify any headers to be returned, which would make it easier to use in testing scenarios where behavior is triggered by headers returned. 

What do you think of these changes?

**Comment by divmain** [comment]
Thanks for the ping, I missed the notification for this somehow.  Merged!

**Comment by divmain** [comment]
And published as `v0.8.0`.

**Comment by biglovisa** [comment]
Awesome, thanks! 👍

**Pull request merged**
